//@version=6
indicator(title="ATR Percentage", shorttitle="ATR%", overlay=false, timeframe="", timeframe_gaps=true, format=format.percent)
length = input.int(title="Length", defval=14, minval=1)
smoothing = input.string(title="Smoothing", defval="RMA", options=["RMA", "SMA", "EMA", "WMA"])

ma_function(source, length) =>
	switch smoothing
		"RMA" => ta.rma(source, length)
		"SMA" => ta.sma(source, length)
		"EMA" => ta.ema(source, length)
		=> ta.wma(source, length)

// Calculate ATR
atr_value = ma_function(ta.tr(true), length)

// Convert to percentage of close price
atr_pct = (atr_value / close) * 100

plot(atr_pct, title = "ATR %", color=color.new(#B71C1C, 0))  