//@version=6
indicator(title="Normalized Average True Range", shorttitle="NATR", overlay=false, timeframe="", timeframe_gaps=true)
length = input.int(title="Length", defval=14, minval=1)
smoothing = input.string(title="Smoothing", defval="RMA", options=["RMA", "SMA", "EMA", "WMA"])
ma_function(source, length) =>
	switch smoothing
		"RMA" => ta.rma(source, length)
		"SMA" => ta.sma(source, length)
		"EMA" => ta.ema(source, length)
		=> ta.wma(source, length)
atr = ma_function(ta.tr(true), length)
natr = (atr / close) * 100
plot(natr, title = "NATR", color=color.new(#B71C1C, 0))

