listen: :3365

acme:
  domains:
    - hyaz.hyas.site
  email: admin@hyas.site

auth:
  type: password
  password: NzPY5nTKThLxUb1MOJTuu6B0

masquerade:
  type: proxy
  proxy:
    url: https://www.bing.com
    rewriteHost: true
