version: "3.8"

services:
  xray-trojan:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray-trojan
    restart: always
    volumes:
      - ./xray-config.json:/etc/xray/config.json
    command: run -c /etc/xray/config.json
    networks:
      - tunnel-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiNWQ3NWFkOTFiYzYyMTA4NmExOTA4OTczNTkwMDUxYzMiLCJ0IjoiOTI5ZDRjMzQtZWJjZi00ZWYyLWI1NWUtODk1NjFhMTJhM2RhIiwicyI6IlRGWi8vVlRCRml4RVBmVXM1NWJBaCtDbjBIN05oYXBtK0ZnSU9SWkMrZlU9In0=
    networks:
      - tunnel-net
    depends_on:
      - xray-trojan

networks:
  tunnel-net:
    driver: bridge
