listen: :443

acme:
  domains:
    - hyaz.hyas.site
  email: admin@hyas.site

auth:
  type: password
  password: NzPY5nTKThLxUb1MOJTuu6B0

masquerade:
  type: proxy
  proxy:
    url: https://www.bing.com
    rewriteHost: true

# Brutal CC hint (Clash client should also set up/down ≈ path capacity)
bandwidth:
  up: 100 mbps
  down: 100 mbps
