# === PROMPT ===
if [ -n "$CURSOR_AGENT" ]; then
  PS1='$ '
else
  PS1="\[\033[1;32m\]\u\[\033[0m\]@\[\033[1;34m\]\h\[\033[0m\] \[\e[1;34m\]\w\[\e[0m\] 🚀🚀🚀  $ "
fi

# === SHELL ===
export EDITOR='cursor'
HISTSIZE=10000
HISTFILESIZE=20000
HISTCONTROL=ignoreboth:erasedups

# === ENV ===
export DISPLAY=:10
export PATH="$HOME/development/flutter/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# === DIR: Core ===
alias al='cd /allah'
alias bl='cd /allah/blue/'

# === DIR: Freqtrade ===
alias ft='cd /allah/freqtrade'
alias ftc='cd /allah/freqtrade/freqtrade'
alias usdt='cd /allah/freqtrade/user_data/data/binance/futures'

# === DIR: Freq Project ===
alias co='cd /allah/blue/freq/project/tools/realtime/tradingview'
alias config='cd /allah/blue/freq/project/user_data/config'
alias conf='cd /allah/blue/freq/project/user_data/config'
alias fq='cd /allah/blue/freq'
alias mi='cd /allah/blue/freq/misc'
alias ml='cd /allah/blue/freq/project/ml_datasets'
alias pro='cd /allah/blue/freq/project'
alias st='cd /allah/blue/freq/project/user_data/strategies'
alias strat='cd /allah/blue/freq/project/user_data/strategies'
alias tools='cd /allah/blue/freq/project/tools'
alias to='cd /allah/blue/freq/project/tools'
alias tv='cd /allah/blue/freq/misc/tradingview'
alias user='cd /allah/blue/freq/project/user_data'
alias tinder='cd /allah/blue/web/tinder'
alias us='cd /allah/blue/freq/project/user_data'

# === DIR: Web ===
alias ba='cd /allah/blue/web/baccarat'
alias decodo='cd /allah/blue/web/proxy/decodo'
alias pr='cd /allah/blue/web/patchright'
alias sm='cd /allah/blue/web/smartproxy'
alias tampermonkey='cd /allah/blue/web/tampermonkey'
alias tm='cd /allah/blue/web/tampermonkey'
alias web='cd /allah/blue/web'

# === DIR: Linux & VPS ===
alias aws='cd /allah/blue/linux/vps/aws'
alias extra='cd /allah/blue/linux/extra'
alias gcp='cd /allah/blue/linux/vps/gcp'
alias li='cd /allah/blue/linux'
alias linode='cd /allah/blue/linux/vps/linode'
alias vps='cd /allah/blue/linux/vps'

# === DIR: Data ===
alias dt='cd /allah/data/ml'

# === Freqtrade Commands ===
alias ftpy='/allah/freqtrade/.venv/bin/python3'
alias ftrun='/allah/freqtrade/.venv/bin/python3 /allah/freqtrade/freqtrade/main.py'

# === Git ===
alias ga='git add'
alias gc='git commit -m'
alias gl='git pull'
alias gp='git push'
alias gs='git status'

# === TensorBoard ===
alias cdtb='cd "$(find . -type d -name "tensorboard" | sort | tail -n 1)"'
alias tb='tensorboard --logdir "$(find . -type d -name "tensorboard" | sort | tail -n 1)"'

# === Utility ===
alias bashrc='cursor /allah/blue/linux/extra/bashrc'
alias cls='clear'
alias code='cursor'
alias diskspace='df -h'
alias ipc="/allah/blue/web/proxy/decodo/ip_checker.sh"
alias lsh='ls -la | head'
alias myip='curl -s http://ipinfo.io/ip'
alias note='cursor /allah/blue/freq/project/note'
alias rc='cursor /allah/blue/linux/extra/bashrc'
