# Aliyun — acme + auth only (listen/masquerade/bandwidth from common defaults)
acme:
  domains:
    - hy.hyas.site
  email: admin@hyas.site
  dir: /etc/hysteria/acme

auth:
  type: password
  password: jEdTlnZe2q2nv1N0lmmXHCp2
